import { useEffect, useMemo, useState } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { ArrowUpRight, Github, Menu, X, Radio, ShieldCheck, Wifi, Send, Copy, Check, Server, Smartphone, Monitor } from 'lucide-react'
import type { Division, Project, NetworkNode } from './data'
import { divisions, githubUrl } from './data'

const apiBase=import.meta.env.VITE_API_URL || (import.meta.env.DEV?'http://localhost:8787':'')

export function Logo(){return <Link className="logo" to="/" aria-label="Pruden Network home"><span className="logo-mark"><img src="/pruden-logo.svg" alt=""/></span><span>PRUDEN <b>NETWORK</b></span></Link>}
export function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><Logo/><nav className={open?'nav-links is-open':'nav-links'} aria-label="Primary navigation"><NavLink to="/network" onClick={()=>setOpen(false)}>Network</NavLink><NavLink to="/projects" onClick={()=>setOpen(false)}>Projects</NavLink><NavLink to="/labs" onClick={()=>setOpen(false)}>Labs</NavLink><NavLink to="/academy" onClick={()=>setOpen(false)}>Academy</NavLink><NavLink to="/community" onClick={()=>setOpen(false)}>Community</NavLink><NavLink to="/studios" onClick={()=>setOpen(false)}>Studios</NavLink><NavLink to="/vault" onClick={()=>setOpen(false)}>Vault</NavLink><Link className="nav-cta" to="/network">Open Console <ArrowUpRight size={15}/></Link></nav><button className="menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>}
export function Footer(){return <footer className="footer"><div className="footer-main"><div><Logo/><p className="footer-tagline">A software network for<br/>connected technology.</p></div><div className="footer-links"><div><small>NETWORK</small><Link to="/network">Console</Link><Link to="/projects">Projects</Link><Link to="/labs">Labs</Link></div><div><small>ECOSYSTEM</small>{divisions.slice(1).map(d=><Link to={d.path} key={d.id}>{d.shortName}</Link>)}</div><div><small>CONNECT</small><a href={githubUrl} target="_blank" rel="noreferrer"><Github size={14}/> GitHub</a><Link to="/contact">Contact</Link></div></div></div><div className="footer-bottom"><span>PRUDEN NETWORK / 2026</span><span>SOFTWARE NETWORK CORE / 0.1.0</span></div></footer>}
export function DivisionCard({division}:{division:Division}){const Icon=division.icon;return <Link className="division-card" to={division.path}><div className="card-top"><span className="icon-box"><Icon size={20}/></span><span className="status"><i/>{division.status}</span></div><h3>{division.name}</h3><p>{division.description}</p><span className="card-link">Explore division <ArrowUpRight size={15}/></span></Link>}
export function ProjectCard({project}:{project:Project}){return <article className="project-card"><div className="project-number">/ {project.id.toUpperCase()}</div><div className="card-top"><span className="eyebrow">{project.category}</span><span className="status"><i/>{project.status}</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="tech-list">{project.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="project-actions">{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noreferrer"><Github size={15}/> Repository</a>}{project.liveUrl?<a href={project.liveUrl} target="_blank" rel="noreferrer">Live <ArrowUpRight size={15}/></a>:<span className="unavailable">Live presence planned</span>}</div></article>}
export function SectionIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function PageFrame({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children:React.ReactNode}){return <><main className="page-shell"><div className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{children}</main><Footer/></>}

type StoredNode={nodeId:string;token:string;name:string}
type Packet={id:string;fromName:string;message:string;timestamp:string;to:string}

export function NetworkConsole(){
 const saved=localStorage.getItem('pruden-node'); const initial=saved?JSON.parse(saved) as StoredNode:null
 const[node,setNode]=useState<StoredNode|null>(initial); const[name,setName]=useState(initial?.name||''); const[nodes,setNodes]=useState<NetworkNode[]>([]); const[message,setMessage]=useState(''); const[target,setTarget]=useState('NETWORK'); const[messages,setMessages]=useState<Packet[]>([]); const[connected,setConnected]=useState(false); const[error,setError]=useState(''); const[copied,setCopied]=useState(false)
 const nodeType=useMemo(()=>/Android|iPhone|Mobile/i.test(navigator.userAgent)?'MOBILE':'WEB',[])
 const loadNodes=async()=>{if(!node)return;try{const r=await fetch(apiBase+'/api/nodes',{headers:{Authorization:'Bearer '+node.token}});if(!r.ok)throw new Error('Authentication failed');const data=await r.json();setNodes(data.nodes);setConnected(true);setError('')}catch(e){setConnected(false);setError(e instanceof Error?e.message:'Network unavailable')}}
 useEffect(()=>{loadNodes()},[node?.token])
 useEffect(()=>{if(!node)return;const source=new EventSource(apiBase+'/api/events?token='+encodeURIComponent(node.token));source.addEventListener('ready',()=>setConnected(true));source.addEventListener('nodes',e=>setNodes(JSON.parse((e as MessageEvent).data)));source.addEventListener('message',e=>setMessages(p=>[...p.slice(-29),JSON.parse((e as MessageEvent).data)]));source.onerror=()=>setConnected(false);return()=>source.close()},[node?.token])
 const register=async()=>{setError('');if(!name.trim())return setError('Give this device a name first.');try{const r=await fetch(apiBase+'/api/nodes/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,type:nodeType})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Registration failed');const next={nodeId:data.nodeId,token:data.token,name:data.node.name};localStorage.setItem('pruden-node',JSON.stringify(next));setNode(next);setNodes([data.node]);setConnected(true)}catch(e){setError(e instanceof Error?e.message:'Could not connect to PRUDEN Network')}}
 const send=async()=>{if(!node||!message.trim())return;try{const r=await fetch(apiBase+'/api/messages',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+node.token},body:JSON.stringify({to:target,message})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessages(p=>[...p.slice(-29),data.packet]);setMessage('')}catch(e){setError(e instanceof Error?e.message:'Message failed')}}
 const disconnect=async()=>{if(!node)return;await fetch(apiBase+'/api/nodes/disconnect',{method:'POST',headers:{Authorization:'Bearer '+node.token}}).catch(()=>{});localStorage.removeItem('pruden-node');setNode(null);setConnected(false);setNodes([])}
 const copyId=async()=>{if(!node)return;await navigator.clipboard?.writeText(node.nodeId);setCopied(true);setTimeout(()=>setCopied(false),1200)}
 if(!node)return <section className="console-card enroll-card"><div className="console-orbit"><Radio size={30}/></div><div><span className="eyebrow">NODE ENROLLMENT</span><h2>CONNECT THIS DEVICE</h2><p>Register this browser as a PRUDEN Network node. It receives a unique network identity and a secure access token.</p><div className="form-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Jark's Workstation" maxLength={48}/><button className="button button-primary" onClick={register}><Wifi size={16}/> Connect node</button></div>{error&&<p className="error-text">{error}</p>}</div></section>
 return <section className="network-console"><div className="console-header"><div><span className="eyebrow">PRUDEN NETWORK CORE / LIVE CONSOLE</span><h2>NETWORK ONLINE <span className={connected?'live-dot':''}/></h2></div><div className="console-actions"><button className="icon-button" onClick={copyId} title="Copy node ID">{copied?<Check size={16}/>:<Copy size={16}/>}</button><button className="button button-ghost" onClick={disconnect}>Disconnect</button></div></div>{error&&<div className="console-error">{error}</div>}<div className="console-grid"><div className="nodes-panel"><div className="panel-label"><span>CONNECTED NODES</span><b>{nodes.filter(n=>n.status==='ONLINE').length}</b></div>{nodes.map(n=><div className="node-row" key={n.nodeId}><span className="node-icon">{n.type==='MOBILE'?<Smartphone size={17}/>:n.type==='WEB'?<Monitor size={17}/>:<Server size={17}/>}</span><div><strong>{n.name}{n.nodeId===node.nodeId?' · THIS NODE':''}</strong><small>{n.nodeId} / {n.type}</small></div><i className={n.status==='ONLINE'?'node-online':''}/></div>)}</div><div className="message-panel"><div className="panel-label"><span>NETWORK LINK</span><ShieldCheck size={15}/></div><div className="message-log">{messages.length===0?<div className="empty-log"><Radio size={22}/><span>Secure channel ready.<br/>Send a packet across PRUDEN Network.</span></div>:messages.map(m=><div className="message-line" key={m.id}><small>{m.fromName} → {m.to} · {new Date(m.timestamp).toLocaleTimeString()}</small><p>{m.message}</p></div>)}</div><div className="message-compose"><select value={target} onChange={e=>setTarget(e.target.value)}><option value="NETWORK">NETWORK BROADCAST</option>{nodes.filter(n=>n.nodeId!==node.nodeId&&n.status==='ONLINE').map(n=><option key={n.nodeId} value={n.nodeId}>{n.name}</option>)}</select><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Transmit a message..." maxLength={1000}/><button className="button button-primary" onClick={send}><Send size={16}/></button></div></div></div><div className="console-footer"><span><ShieldCheck size={14}/> AUTHENTICATED NODE</span><span>NODE ID <b>{node.nodeId}</b></span><span>TRANSPORT HTTPS + SSE</span></div></section>
}